CREATE_RESULT_TABLE = '''
    CREATE TABLE IF NOT EXISTS result (
        user_id INTEGER PRIMARY KEY,
        success INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        postponed INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        refused INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        invite_friend INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        transfer_abroad INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        mobile_bank INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        debit_card INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        credit_card INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        sim_card INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        investments INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        junior INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        subscription INTEGER UNSIGNED DEFAULT 0 NOT NULL,
        card_protection INTEGER UNSIGNED DEFAULT 0 NOT NULL 
    );
'''

GET_ALL_USER_IDS = '''
    SELECT user_id
    FROM result;
'''
