name: Build

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Build ans push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest
